### ISSUE TITLE
Observe mode events

### ISSUE THREAD

**Issue by norro** [MROS-RobMoSys-ITP/mros_modes_observer#1]
Currently, the mode observer observes all `/{node}/transition_event` topics to observe state transition, e.g., going to active, inactive or error-processing. This way it is observing all *state* transitions, however, it is missing all *mode* changes.

The observer should additionally observe `/{node}/mode_event` topics to observe mode changes, e.g., a node going from normal mode to degraded mode. Messages sent on this topic are of type [ModeEvent](https://github.com/micro-ROS/system_modes/blob/master/system_modes/msg/ModeEvent.msg) and very close to the TransitionEvent messages.

**Comment by marioney** [comment]
> The observer should additionally observe `/{node}/mode_event` topics to observe mode changes, e.g., a node going from normal mode to degraded mode. Messages sent on this topic are of type [ModeEvent](https://github.com/micro-ROS/system_modes/blob/master/system_modes/msg/ModeEvent.msg) and very close to the TransitionEvent messages.

This should not be too complicated, but I have a couple questions:

- Should we read the `/{node}/mode_event` for the same nodes/systems as the `/{node}/transition_event` or should we have a separated list on the [`components.yaml`](https://github.com/MROS-RobMoSys-ITP/mros_modes_observer/blob/main/params/components.yaml) file?
- What transitions should we look for when sending a diagnostics error? (i.e. For the `/{node}/transition_event` we're only checking the `lifecycle_msgs::msg::State::TRANSITION_STATE_ERRORPROCESSING` to `lifecycle_msgs::msg::State::PRIMARY_STATE_UNCONFIGURED`)

**Comment by norro** [comment]
If you currently only rely on `error` and `inactive`, this is fine I guess.
Metacontrol might want to react on nodes/systems going into a certain (degraded?) mode. In the Bosch Pilot, we planed for this up to now.

@chcorbato what do you think?

**Comment by chcorbato** [comment]
I think de answer depends on how we decide to use metacontrol and system modes:

1. If it is a design decision to have the system transition to certain "degraded" modes when necessary, independently of the metacontrol, then I think we need to also observe these events for the metacontrol to have an appropriate response to it.

2. But if we decide that any system adaptation, including all mode transitions, can only be initiated by the metacontrol, then I guess there would be no need to observe it, apart from maybe observe it to confirm the success of a requested mode transition.

What would be your preferred design @norro ?

**Comment by norro** [comment]
I think you're right, Carlos, this is indeed a design decision. And when you put it like that I would suggest we go for the 2. option to have it more consistent.
So this issue is then more of a enhancement, which is probably not required in the near future - not even for the Bosch pilot.

**Comment by norro** [comment]
Superseeded by https://github.com/MROS-RobMoSys-ITP/mros_modes_observer/issues/2
